# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40045f67860561e72ca19cb1283952991fd47cb6b3fb1902e93611c3c20ea517ba5c49f19da36c2e686edb0d911a6d2cd0c5a2da4e3df9a81f05bde25c4bd7d4

test:
  secret_key_base: bd97b983509f1dba765b391bbf134718c338fef9359762b60585a0f0a130e8de0a487ba97c40996b7d958277b94bcd3298b09f43ca2179a926f3a22cc8e8bae7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
